### ISSUE TITLE
No "black.png"

### ISSUE THREAD

**Issue by Killerqu00** [mattestanka/Among-Us-Helper#1]
![изображение](https://user-images.githubusercontent.com/47712032/95182745-af8ee600-07cd-11eb-97e3-b0be2a1d6171.png)

**Comment by Killerqu00** [comment]
If I copy-paste pictures from "resources" to the folder with code file, everything works.

**Comment by mattestanka** [comment]
Yeah I have to set the directory in the code for now just run the code inside the resources folder

**Comment by mattestanka** [comment]
Yeah I have to set the directory in the code for now just run the code inside the resources folder

**Comment by mattestanka** [comment]
I fixed it in v 0.02
